# Generated by Django 2.2 on 2020-02-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=50)),
                ('author_book', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='bookerisell')),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
