# Generated by Django 2.2 on 2020-02-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_title', models.CharField(max_length=50)),
                ('history_author', models.CharField(max_length=50)),
                ('history_image', models.ImageField(upload_to='bookerisell')),
                ('history_amount', models.IntegerField()),
            ],
        ),
    ]
