# Generated by Django 2.2 on 2020-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksell', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiction_title', models.CharField(max_length=50)),
                ('fiction_author', models.CharField(max_length=50)),
                ('fiction_image', models.ImageField(upload_to='bookerisell')),
                ('fiction_amount', models.IntegerField()),
            ],
        ),
    ]
