# Generated by Django 2.2 on 2020-02-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksell', '0003_fiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_title', models.CharField(max_length=50)),
                ('detail_author', models.CharField(max_length=50)),
                ('detail_image', models.ImageField(upload_to='bookerisell')),
                ('detail_amount', models.IntegerField()),
            ],
        ),
    ]
