# Generated by Django 2.2 on 2020-02-19 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksell', '0004_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
