# Generated by Django 2.2 on 2020-02-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksell', '0006_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
