# Generated by Django 2.2 on 2020-02-20 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booksell', '0007_delete_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_author',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bookerisell'),
            preserve_default=False,
        ),
    ]
